[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "migration"
publish.workspace = true
version.workspace = true

[dependencies]
sea-orm-migration = {workspace = true, features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
]}
