[package]
name = "migration"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
sea-orm-migration = { workspace = true, features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
