[database]
address = "pg-stable.Veloquent.secoder.local"
max_connections = 100
name = "veloquent"
password = "123456"
port = 5432
username = "yangzheh"

[listen]
address = "0.0.0.0"
port = 80

[authentication]
exp_after = 86400
secret = "secret"

[upload]
dir = "/srv/veloquent/upload"
