[database]
username = "yangzheh"
password = "123456"
address = "127.0.0.1"
port = 5432
name = "veloquent"
max_connections = 10

[listen]
address = "127.0.0.1"
port = 8000

[authentication]
secret = "secret"
exp_after = 86400
