[database]
address = "127.0.0.1"
max_connections = 10
name = "veloquent"
password = "123456"
port = 5432
username = "yangzheh"

[listen]
address = "0.0.0.0"
port = 8000

[authentication]
exp_after = 86400
secret = "secret"

[upload]
dir = "/srv/veloquent/upload"
