//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::contact::Entity as Contact;
pub use super::feed::Entity as Feed;
pub use super::message::Entity as Message;
pub use super::session::Entity as Session;
pub use super::upload::Entity as Upload;
pub use super::user::Entity as User;
